#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Pruv — Local 3-node P2P test
#
# Starts 3 nodes on the same machine, each on a different port.
# Node 1 is the "seed" (bootstrap) node.
# Nodes 2 & 3 dial Node 1 via bootstrap peer addr.
# All logs go to local-test/node{1,2,3}.log
# Press Ctrl-C or wait 60 seconds for auto-shutdown.
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BIN="$ROOT/node-software/target/release/pruv-node"

if [[ ! -f "$BIN" ]]; then
  echo "ERROR: Binary not found at $BIN"
  echo "Run: cargo build --manifest-path node-software/Cargo.toml --release"
  exit 1
fi

# ── Port availability check ────────────────────────────────────────────────────
echo "Checking port availability..."
PORTS_NEEDED=(9000 9001 9002 9090 9091 9092)
PORT_ERROR=0
for PORT in "${PORTS_NEEDED[@]}"; do
  if lsof -ti:"$PORT" &>/dev/null; then
    OCCUPANT=$(lsof -ti:"$PORT" | head -1)
    echo "ERROR: Port $PORT is already in use by PID $OCCUPANT"
    echo "  Kill it with: kill $OCCUPANT"
    PORT_ERROR=1
  fi
done
if [[ "$PORT_ERROR" -eq 1 ]]; then
  echo "Resolve port conflicts above, then re-run."
  exit 1
fi
echo "All ports (${PORTS_NEEDED[*]}) are free."

mkdir -p "$SCRIPT_DIR/logs"

# ── Keypairs (generated by solana-keygen) ─────────────────────────────────────
NODE1_KP='[177,102,130,1,251,55,111,70,40,58,25,130,66,138,107,185,24,121,120,231,212,166,128,211,107,37,76,54,230,76,139,144,32,101,214,96,142,151,65,230,100,179,182,230,158,103,43,62,232,40,234,118,98,142,86,205,173,89,188,1,6,232,179,163]'
NODE2_KP='[179,230,202,221,163,192,29,92,156,209,229,52,188,0,17,247,112,44,118,147,58,55,18,191,19,205,145,25,231,16,3,110,177,239,110,104,234,61,139,219,251,91,132,190,155,150,170,190,237,242,170,220,126,85,244,216,95,240,212,127,117,39,73,2]'
NODE3_KP='[188,133,226,144,193,160,167,153,45,249,19,152,27,11,100,102,140,213,37,213,158,85,185,183,186,135,183,109,58,104,111,145,133,11,56,152,45,238,40,179,67,159,232,114,227,226,128,196,80,110,222,194,136,148,155,181,53,119,57,43,254,62,41,121]'

# Node 1 PeerId (deterministic from keypair — confirmed from first run)
NODE1_PEER_ID="12D3KooWBzqHEQ1QjzRSmHVoSrQxVa4JXqJqQPFB6DUFww4JXuvr"

# Bootstrap peer multiaddr for nodes 2 & 3
BOOTSTRAP="/ip4/127.0.0.1/tcp/9000/p2p/${NODE1_PEER_ID}"

# ── Shared Solana config ───────────────────────────────────────────────────────
COMMON_ENV=(
  SOLANA_RPC_URL=https://api.devnet.solana.com
  REGISTRY_PROGRAM_ID=Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS
  ATTESTATION_PROGRAM_ID=Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnT
  GOVERNANCE_PROGRAM_ID=Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnU
  NODE_PROGRAM_ID=Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnV
  SRS_K=10
  ATTESTATION_INTERVAL_SECS=3600
  "RUST_LOG=info,pruv_node=debug"
)

PIDS=()
cleanup() {
  echo ""
  echo "─── Shutting down all nodes ───────────────────────────────────────────"
  for pid in "${PIDS[@]}"; do
    kill "$pid" 2>/dev/null || true
  done
  wait "${PIDS[@]}" 2>/dev/null || true
  echo "─── All nodes stopped ─────────────────────────────────────────────────"
  echo ""
  echo "Logs saved to $SCRIPT_DIR/logs/"
  echo "  node1.log  node2.log  node3.log"
  echo ""
  echo "Check for gossip events:"
  grep -h "P2P\|heartbeat\|connected\|mDNS\|subscribed" \
       "$SCRIPT_DIR/logs/node1.log" \
       "$SCRIPT_DIR/logs/node2.log" \
       "$SCRIPT_DIR/logs/node3.log" 2>/dev/null \
    | sort -t'T' -k2 | head -60 || true
}
trap cleanup INT TERM EXIT

echo "══════════════════════════════════════════════════════════════════════════"
echo "  Pruv — Local 3-Node P2P Test"
echo "══════════════════════════════════════════════════════════════════════════"

# ── Start Node 1 (seed / bootstrap node) ─────────────────────────────────────
echo "[Node 1] Starting on :9000  metrics :9090  (seed node, no bootstrap peers)"
env "${COMMON_ENV[@]}" \
  OPERATOR_KEYPAIR="$NODE1_KP" \
  P2P_PORT=9000 \
  METRICS_PORT=9090 \
  "$BIN" > "$SCRIPT_DIR/logs/node1.log" 2>&1 &
PIDS+=($!)
echo "[Node 1] PID=${PIDS[-1]}  PeerId=$NODE1_PEER_ID"

# Give Node 1 time to bind its port before others dial it
sleep 2

# ── Start Node 2 ──────────────────────────────────────────────────────────────
echo "[Node 2] Starting on :9001  metrics :9091  bootstrap → $BOOTSTRAP"
env "${COMMON_ENV[@]}" \
  OPERATOR_KEYPAIR="$NODE2_KP" \
  P2P_PORT=9001 \
  METRICS_PORT=9091 \
  BOOTSTRAP_PEERS="$BOOTSTRAP" \
  "$BIN" > "$SCRIPT_DIR/logs/node2.log" 2>&1 &
PIDS+=($!)
echo "[Node 2] PID=${PIDS[-1]}"

sleep 1

# ── Start Node 3 ──────────────────────────────────────────────────────────────
echo "[Node 3] Starting on :9002  metrics :9092  bootstrap → $BOOTSTRAP"
env "${COMMON_ENV[@]}" \
  OPERATOR_KEYPAIR="$NODE3_KP" \
  P2P_PORT=9002 \
  METRICS_PORT=9092 \
  BOOTSTRAP_PEERS="$BOOTSTRAP" \
  "$BIN" > "$SCRIPT_DIR/logs/node3.log" 2>&1 &
PIDS+=($!)
echo "[Node 3] PID=${PIDS[-1]}"

echo ""
echo "══════════════════════════════════════════════════════════════════════════"
echo "  All 3 nodes running. Tailing merged logs (Ctrl-C to stop)..."
echo "  Gossip mesh forms after ~10s. Heartbeats broadcast every 30s."
echo "══════════════════════════════════════════════════════════════════════════"
echo ""

# ── Tail merged logs with node prefix ────────────────────────────────────────
sleep 1
tail -F \
  "$SCRIPT_DIR/logs/node1.log" \
  "$SCRIPT_DIR/logs/node2.log" \
  "$SCRIPT_DIR/logs/node3.log" \
  2>/dev/null &
TAIL_PID=$!

# Auto-shutdown after 60 seconds
sleep 60
kill $TAIL_PID 2>/dev/null || true
# cleanup called by EXIT trap